### ISSUE TITLE
Add loopback-connector-db2 to CI

### ISSUE THREAD

**Issue by chandadharap** [strongloop/loopback-connector-db2#5]
- [x] Add to ci @rmg to help
- [x] Fix test failures
- [x] Verify appropriate license

**Comment by rmg** [comment]
loopback-datasource-juggler@2 has a dev dependency on bluebird@^2.9.9 which is required for running the imported tests. It will have to be added as a devDependency to this module. This is currently blocking CI from producing any useful results, since it causes a failure at the start of `npm test`.

**Comment by qpresley** [comment]
@rmg This connector has bluebird@^2.9.9 as a devDependency.

**Comment by qpresley** [comment]
@rmg @chandadharap I've been looking at fixing the CI failures and it looks like the SQLDB environment we run the CI tests against is going to be a limitation.  SQLDB has a 10 concurrent database connection limit.  Since Mocha executes ALL tests in parallel it attempts to connect roughly 35 times concurrently which results in many of the test suites failing.

There are some other concerns I have with using SQLDB as the underlying data source however they are minor compared to the problem above.  At this point I'm not real sure what a good solution is for this since the CI tests are run in an environment where we don't have a full DB2 install available.

**Comment by qpresley** [comment]
Latest CI runs have been clean for this connector
